services:
  - type: web
    name: jewelry-store-management
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile.txt
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
